services:
  pgdb:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: termtable
      POSTGRES_DB: termtable
    ports:
      - "5432:5432"
    volumes:
      - termtabledata:/var/lib/postgresql/data
      - ./data/postgres:/docker-entrypoint-initdb.d

volumes:
  termtabledata:
